repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: local
  hooks:
  - id: add-header
    name: Run `add_header` script
    description: Run the `add_header` script to verify the file headers
    entry: tools/add_header
    language: system
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.3
  hooks:
    - id: ruff
      args: [ --fix ]
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.2.33
  hooks:
    - id: pip-compile
      name: pip-compile requirements.server
      args: [requirements/requirements.server.in, -o, requirements/requirements.server.txt, -q]
      # `files` tells the hook to only run if files matching the pattern have been modified
      files: ^requirements/requirements.server\.(in|txt)$
    - id: pip-compile
      name: pip-compile requirements.dev
      args: [requirements/requirements.dev.in, -o, requirements/requirements.dev.txt, -q]
      files: ^requirements/requirements.dev\.(in|txt)$
